### PR TITLE
Filter SVG and use dotx

### PR DESCRIPTION
**Pull request by dagoss**
- Changes to not include .svg images, which are not supported by Word, and will prevent the output from being opened if included.
- Changed the template from a dotm to a dotx. Some users (and organizations with zealous security policies) will not trust a docm. I created the dotx by saving the original dotm using Word 2007, so everything about it should be identical. I ran a few maps through and didn't notice any formatting issues

### CODE REVIEW

**Comment by AirQuick** [comment]
Useful changes.
I think when filtering SVG, a warning message should be emitted to the console.

**Comment by jelovirt** [comment]
Svg should be ignored with warning for now. In future the code should convert svg into some format word supports.

**Comment by robertnthomas** [comment]
I have created a new plugin called [com.tagsmiths.ooxml.svg2png](https://github.com/robertnthomas/com.tagsmiths.ooxml.svg2png.git) that uses ImageMagick to convert from SVG to PNG. I made some changes to [com.elovirta.ooxml on my fork](https://github.com/robertnthomas/com.elovirta.ooxml.git) to integrate the plugin.

Right now, I only have tested svg2png using Ubuntu Linux 16.04 and Windows 10. The Ubuntu support is at ImageMagick-6.8.9 rather than the current 7.0.3-4 version because that version of the convert executable was throwing missing delegate errors. I need to see whether I can find a Linux binary for portable ImageMagick.

I no longer have access to an OS-X machine. But, it should be straight forward to install ImageMagick and point ant property ImageMagickExecutable to the convert executable.

If you are interested in incorporating com.tagsmiths.ooxml.svg2png into com.elovirta.ooxml, I'll abandon com.tagsmiths.ooxml.svg2png. I am also willing to do the integration work on my fork and open a pull request.

My com.elovirta.ooxml fork also implements a true/false ant property for topic numbering.

**Comment by jelovirt** [comment]
#19 adds support for SVG. Closing this as obsolete. Using a dotx template by default will be handled in a different issue/PR.

**Pull request closed without merging**
