### PR TITLE
Use property names compatible with DITA OT 4.x

### PR DESCRIPTION
**Pull request by raducoravu**
Fix for #101, use property names compatible with DITA OT 4.x

Signed-off-by: Radu Coravu <radu_coravu@sync.ro>

### CODE REVIEW

**Comment by jelovirt** [comment]
Looks good, but it then means it will not work for 3.x versions of DITA-OT. I'm thinking whether this is something that I should care about, because my preference would be to push people to upgrade. One option would be to have a conditional initialization based on `${otversion}` property that's the version of DITA-OT. So something like (untested)

```
<!-- Skip image and HTML copy in DITA-OT 3.x or older -->
<condition property="preprocess.copy-image.skip" value="false">
  <matches string="${otversion}" pattern="^[123]\."/>
</condition>
<condition property="preprocess.copy-html.skip" value="false">
  <matches string="${otversion}" pattern="^[123]\."/>
</condition>
<!-- Skip image and HTML copy in DITA-OT 4.x or newer -->
<condition property="build-step.copy-image" value="false">
  <matches string="${otversion}" pattern="^[^123]\."/>
</condition>
<condition property="build-step.copy-html" value="false">
  <matches string="${otversion}" pattern="^[^123]\."/>
</condition>
```

@raducoravu are you able to verify if this would work and make the change to the PR?

**Comment by raducoravu** [comment]
@jelovirt not sure if I have the time to work more on this today. How about if we just double the property definitions and avoid the regexp matches? I do not see a harm in doing that.
  
     <property name="preprocess.copy-image.skip" value="true"/>
     <property name="preprocess.copy-html.skip" value="true"/>
     <property name="build-step.copy-image" value="false"/>
     <property name="build-step.copy-html" value="false"/>

**Comment by jelovirt** [comment]
That will not work, it will throw

> [DOTA015F][FATAL] Internal property preprocess.copy-html.skip may not be set directly. Use property build-step.copy-html instead.

**Comment by raducoravu** [comment]
Closing the PR as #104 has a more complete solution.

**Pull request closed without merging**
